dist: trusty
language: node_js
node_js:
- stable
node_js:
- stable
script:
- npm run coverage
after_success:
- npm run publish-coverage
notifications:
   email:
      recipients:
      - one@example.com      # change to your own address
      - other@example.com    # uae other (optional)
      on_success: never        # default: change
      on_failure: always       # default: always